/**
 * Step: admin — Configure admin dashboard username, password, and landing page.
 * Also generates Caddy config if domain is provided.
 *
 * Usage:
 *   npx tsx setup/index.ts --step admin -- --username USER --password PASS
 *   npx tsx setup/index.ts --step admin -- --username USER --password PASS --domain example.com --port 9743
 */
import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';

import { logger } from '../src/logger.js';
import { SetupStepResult } from '../src/setup-state.js';
import { emitStatus } from './status.js';

function parseArgs(args: string[]): {
  username: string;
  password: string;
  domain: string;
  port: string;
} {
  let username = '';
  let password = '';
  let domain = '';
  let port = '9743';
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--username' && args[i + 1]) username = args[++i];
    if (args[i] === '--password' && args[i + 1]) password = args[++i];
    if (args[i] === '--domain' && args[i + 1]) domain = args[++i];
    if (args[i] === '--port' && args[i + 1]) port = args[++i];
  }
  return { username, password, domain, port };
}

function updateEnvFile(key: string, value: string): void {
  const envPath = path.join(process.cwd(), '.env');
  let content = '';
  try {
    content = fs.readFileSync(envPath, 'utf-8');
  } catch {
    content = '';
  }

  const activeRegex = new RegExp(`^${key}=.*$`, 'm');
  const commentedRegex = new RegExp(`^#\\s*${key}=.*$`, 'm');

  if (activeRegex.test(content)) {
    content = content.replace(activeRegex, `${key}=${value}`);
  } else if (commentedRegex.test(content)) {
    content = content.replace(commentedRegex, `${key}=${value}`);
  } else {
    content = content.trimEnd() + `\n${key}=${value}\n`;
  }

  fs.writeFileSync(envPath, content);
}

export async function run(args: string[]): Promise<SetupStepResult> {
  const { username, password, domain, port } = parseArgs(args);
  const projectRoot = process.cwd();

  // Check if already configured
  const envPath = path.join(projectRoot, '.env');
  let envContent = '';
  try {
    envContent = fs.readFileSync(envPath, 'utf-8');
  } catch {
    /* ok */
  }

  const hasUsername = /^ADMIN_USERNAME=.+/m.test(envContent);
  const hasPassword = /^ADMIN_PASSWORD_HASH=.+/m.test(envContent);

  if (hasUsername && hasPassword && !username && !password) {
    emitStatus('ADMIN', {
      STATUS: 'already_configured',
      USERNAME: envContent.match(/^ADMIN_USERNAME=(.+)$/m)?.[1] || '',
    });
    return { status: 'already_configured' };
  }

  if (!username || !password) {
    emitStatus('ADMIN', {
      STATUS: 'input_required',
      MESSAGE:
        'Admin username and password needed. Use --username and --password flags.',
    });
    return {
      status: 'input_required',
      message:
        'Admin username and password needed. Use --username and --password flags.',
    };
  }

  // Set credentials
  const hash = await bcrypt.hash(password, 12);
  updateEnvFile('ADMIN_USERNAME', username);
  updateEnvFile('ADMIN_PASSWORD_HASH', hash);
  logger.info({ username }, 'Admin credentials configured');

  // Update landing page config with assistant name
  const assistantName =
    envContent.match(/^ASSISTANT_NAME="?([^"\n]+)"?$/m)?.[1] || 'NanoCrab';
  const siteStaticDir = path.join(projectRoot, 'site', 'static');
  fs.mkdirSync(siteStaticDir, { recursive: true });
  fs.writeFileSync(
    path.join(siteStaticDir, 'config.json'),
    JSON.stringify({ name: assistantName }),
  );

  // Generate Caddy config if domain provided
  if (domain) {
    const internalPort =
      envContent.match(/^ADMIN_PORT=(\d+)$/m)?.[1] || '9744';
    const caddyConfig = `# NanoCrab Caddy configuration
# Generated by: npx tsx setup/index.ts --step admin

# Public landing page
${domain} {
    root * ${projectRoot}/site
    file_server
}

# Admin dashboard (SSL on custom port)
${domain}:${port} {
    reverse_proxy localhost:${internalPort}
}
`;
    const caddyPath = path.join(projectRoot, 'Caddyfile');
    fs.writeFileSync(caddyPath, caddyConfig);
    logger.info({ domain, port }, 'Caddy config generated at Caddyfile');

    emitStatus('ADMIN', {
      STATUS: 'success',
      USERNAME: username,
      DOMAIN: domain,
      PORT: port,
      CADDY_CONFIG: caddyPath,
      MESSAGE: `Credentials set. Caddy config written to ${caddyPath}. Run: sudo cp ${caddyPath} /etc/caddy/Caddyfile && sudo systemctl reload caddy`,
    });
    return { status: 'success' };
  } else {
    emitStatus('ADMIN', {
      STATUS: 'success',
      USERNAME: username,
    });
    return { status: 'success' };
  }
}
